baseurl = "https://www.else.so"
languageCode = "zh-cn"
theme = "breeze"
title = "ELSE"
DefaultContentLanguage = "zh"
paginate = 12


[params]
    launchDate = 1606500247
    copyright = "else.so"
    github = "koho"
    email = "gerhard@else.so"
    tgId = "1468317831"
    logoName = "ELSE"
    math = true

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "文章"
        url = "/"
        weight = -100
    [[menu.main]]
        identifier = "tags"
        name = "标签"
        url = "tags/"
        weight = -90
    [[menu.main]]
        identifier = "archives"
        name = "归档"
        url = "archives/"
        weight = -80
    [[menu.main]]
        identifier = "about"
        name = "关于"
        url = "about/"
        weight = -70

[taxonomies]
    tag = "tags"
    archive = "archives"

[markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
    style = "manni"
