# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Breeze"
license = "MIT"
licenselink = "https://github.com/koho/blog/blob/master/themes/breeze/LICENSE"
description = "Another simple hugo theme"
homepage = "https://xhat.org"
tags = ["Simple"]
features = []
min_version = "0.41.0"

[author]
  name = "koho"
  homepage = "https://xhat.org"
