name: Blog

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup environment
        run: sudo snap install hugo

      - name: Build site
        run: hugo
      
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: |
            ./public/
            ./isso.cfg
          
  deploy:
    needs: [build]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./blog
      
      - name: Deploy site
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.SERVER }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
          USER: ${{ secrets.USER }}
        run: |
          tar czf public.tar.gz ./blog
          eval `ssh-agent -s`
          echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
          scp -o StrictHostKeyChecking=no ./public.tar.gz $USER@$SERVER:$TARGET_DIR
          ssh -o StrictHostKeyChecking=no $USER@$SERVER "rm -rf $TARGET_DIR/public; tar zxf $TARGET_DIR/public.tar.gz; systemctl restart isso"
