name: Blog

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup environment
        run: sudo snap install hugo

      - name: Build site
        run: hugo
      
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./public/
          
  deploy:
    needs: [build]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./public
      
      - name: Deploy site
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.SERVER }}
        run: |
          tar czf public.tar.gz ./public
          eval `ssh-agent -s`
          echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
          ssh-keygen -R $SERVER
          scp ./public.tar.gz root@$SERVER:/root
